/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as insureSol from "./Insure.sol";
export type { insureSol };
import type * as oracleSol from "./Oracle.sol";
export type { oracleSol };
export type { CustomOracle } from "./CustomOracle";
export type { DAI } from "./DAI";
