/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CustomOracle,
  CustomOracleInterface,
} from "../../../contracts/Insure.sol/CustomOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_expiry",
        type: "uint256",
      },
    ],
    name: "getExpiryPriceLevel",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CustomOracle__factory {
  static readonly abi = _abi;
  static createInterface(): CustomOracleInterface {
    return new utils.Interface(_abi) as CustomOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CustomOracle {
    return new Contract(address, _abi, signerOrProvider) as CustomOracle;
  }
}
