/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as customOracleSol from "./CustomOracle.sol";
export * as insureSol from "./Insure.sol";
export * as oracleSol from "./Oracle.sol";
export { DAI__factory } from "./DAI__factory";
