/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CustomOracle__factory } from "./CustomOracle__factory";
export { Oracle__factory } from "./Oracle__factory";
