/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./@chainlink";
export type { chainlink };
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { AggregatorV3Interface } from "./@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface";
export { AggregatorV3Interface__factory } from "./factories/@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface__factory";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { ERC20 } from "./@openzeppelin/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory";
export type { IERC20Metadata } from "./@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { CustomOracle } from "./contracts/CustomOracle";
export { CustomOracle__factory } from "./factories/contracts/CustomOracle__factory";
export type { DAI } from "./contracts/DAI";
export { DAI__factory } from "./factories/contracts/DAI__factory";
export type { Insure } from "./contracts/Insure.sol/Insure";
export { Insure__factory } from "./factories/contracts/Insure.sol/Insure__factory";
export type { PriceConsumerV3 } from "./contracts/Oracle.sol/PriceConsumerV3";
export { PriceConsumerV3__factory } from "./factories/contracts/Oracle.sol/PriceConsumerV3__factory";
